### ISSUE TITLE
Issue with setting title in nib.

### ISSUE THREAD

**Issue by yakubbaev** [lurado/LDONavigationSubtitleView#2]
If you set title of view controller in nib, it does not get propagated to LDONavigationSubtitleVeiw.title.

**Comment by sebastianludwig** [comment]
Did you connect the `viewController` outlet of the subtitle view? I already updated the readme to point out it that's necessary.

**Comment by yakubbaev** [comment]
If I change watched property `title` to `navigationItem.title` it works.
It's bad idea to catch viewController and add observers to it. I'm going to add separate issue for that.

**Comment by sebastianludwig** [comment]
If you set the `title` property in IB on the view controller itself, it worked. If you however set the `title` property on the view controllers navigation item (also in IB) it didn't.

I added KVO vor `navigationItem.title` as well and using either `vc.title` or `vc.navigationItem.title` (whichever is set) when setting the `viewController` reference.

I released 1.2.4.

**Comment by yakubbaev** [comment]
Thank you for quick response!

**Comment by sebastianludwig** [comment]
Thank you for reporting the issue :-)

**Comment by yakubbaev** [comment]
But it doesn't seem to fix the issue.

**Comment by sebastianludwig** [comment]
Mh - it does work for me. Can you provide a broken sample project?
